// Generated by jextract

package com.nativecloud.sync;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class sync_h {

    sync_h() {
        // Should not be called directly
    }

    static final Arena LIBRARY_ARENA = Arena.ofAuto();
    static final boolean TRACE_DOWNCALLS = Boolean.getBoolean("jextract.trace.downcalls");

    static void traceDowncall(String name, Object... args) {
         String traceArgs = Arrays.stream(args)
                       .map(Object::toString)
                       .collect(Collectors.joining(", "));
         System.out.printf("%s(%s)\n", name, traceArgs);
    }

    static MemorySegment findOrThrow(String symbol) {
        return SYMBOL_LOOKUP.find(symbol)
            .orElseThrow(() -> new UnsatisfiedLinkError("unresolved symbol: " + symbol));
    }

    static MethodHandle upcallHandle(Class<?> fi, String name, FunctionDescriptor fdesc) {
        try {
            return MethodHandles.lookup().findVirtual(fi, name, fdesc.toMethodType());
        } catch (ReflectiveOperationException ex) {
            throw new AssertionError(ex);
        }
    }

    static MemoryLayout align(MemoryLayout layout, long align) {
        return switch (layout) {
            case PaddingLayout p -> p;
            case ValueLayout v -> v.withByteAlignment(align);
            case GroupLayout g -> {
                MemoryLayout[] alignedMembers = g.memberLayouts().stream()
                        .map(m -> align(m, align)).toArray(MemoryLayout[]::new);
                yield g instanceof StructLayout ?
                        MemoryLayout.structLayout(alignedMembers) : MemoryLayout.unionLayout(alignedMembers);
            }
            case SequenceLayout s -> MemoryLayout.sequenceLayout(s.elementCount(), align(s.elementLayout(), align));
        };
    }


    static {
        System.loadLibrary("sync");
    }

    static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.loaderLookup()
            .or(Linker.nativeLinker().defaultLookup());

    public static final ValueLayout.OfBoolean C_BOOL = ValueLayout.JAVA_BOOLEAN;
    public static final ValueLayout.OfByte C_CHAR = ValueLayout.JAVA_BYTE;
    public static final ValueLayout.OfShort C_SHORT = ValueLayout.JAVA_SHORT;
    public static final ValueLayout.OfInt C_INT = ValueLayout.JAVA_INT;
    public static final ValueLayout.OfLong C_LONG_LONG = ValueLayout.JAVA_LONG;
    public static final ValueLayout.OfFloat C_FLOAT = ValueLayout.JAVA_FLOAT;
    public static final ValueLayout.OfDouble C_DOUBLE = ValueLayout.JAVA_DOUBLE;
    public static final AddressLayout C_POINTER = ValueLayout.ADDRESS
            .withTargetLayout(MemoryLayout.sequenceLayout(java.lang.Long.MAX_VALUE, JAVA_BYTE));
    public static final ValueLayout.OfLong C_LONG = ValueLayout.JAVA_LONG;
    /**
     * {@snippet lang=c :
     * typedef long ptrdiff_t
     * }
     */
    public static final OfLong ptrdiff_t = sync_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef unsigned long size_t
     * }
     */
    public static final OfLong size_t = sync_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef int wchar_t
     * }
     */
    public static final OfInt wchar_t = sync_h.C_INT;

    private static class upload_file {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            sync_h.C_INT,
            sync_h.C_POINTER,
            sync_h.C_POINTER,
            sync_h.C_POINTER,
            sync_h.C_POINTER
        );

        public static final MemorySegment ADDR = sync_h.findOrThrow("upload_file");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int upload_file(const char *local_path, const char *nextcloud_url, const char *username, const char *password)
     * }
     */
    public static FunctionDescriptor upload_file$descriptor() {
        return upload_file.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int upload_file(const char *local_path, const char *nextcloud_url, const char *username, const char *password)
     * }
     */
    public static MethodHandle upload_file$handle() {
        return upload_file.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int upload_file(const char *local_path, const char *nextcloud_url, const char *username, const char *password)
     * }
     */
    public static MemorySegment upload_file$address() {
        return upload_file.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int upload_file(const char *local_path, const char *nextcloud_url, const char *username, const char *password)
     * }
     */
    public static int upload_file(MemorySegment local_path, MemorySegment nextcloud_url, MemorySegment username, MemorySegment password) {
        var mh$ = upload_file.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("upload_file", local_path, nextcloud_url, username, password);
            }
            return (int)mh$.invokeExact(local_path, nextcloud_url, username, password);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class download_file {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            sync_h.C_POINTER,
            sync_h.C_POINTER,
            sync_h.C_POINTER,
            sync_h.C_POINTER
        );

        public static final MemorySegment ADDR = sync_h.findOrThrow("download_file");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void download_file(const char *nextcloud_url, const char *local_path, const char *username, const char *password)
     * }
     */
    public static FunctionDescriptor download_file$descriptor() {
        return download_file.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void download_file(const char *nextcloud_url, const char *local_path, const char *username, const char *password)
     * }
     */
    public static MethodHandle download_file$handle() {
        return download_file.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void download_file(const char *nextcloud_url, const char *local_path, const char *username, const char *password)
     * }
     */
    public static MemorySegment download_file$address() {
        return download_file.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void download_file(const char *nextcloud_url, const char *local_path, const char *username, const char *password)
     * }
     */
    public static void download_file(MemorySegment nextcloud_url, MemorySegment local_path, MemorySegment username, MemorySegment password) {
        var mh$ = download_file.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("download_file", nextcloud_url, local_path, username, password);
            }
            mh$.invokeExact(nextcloud_url, local_path, username, password);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class list_files {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            sync_h.C_INT,
            sync_h.C_POINTER,
            sync_h.C_POINTER,
            sync_h.C_POINTER,
            sync_h.C_POINTER,
            sync_h.C_LONG
        );

        public static final MemorySegment ADDR = sync_h.findOrThrow("list_files");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int list_files(const char *url, const char *user, const char *pass, char *outBuffer, size_t outSize)
     * }
     */
    public static FunctionDescriptor list_files$descriptor() {
        return list_files.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int list_files(const char *url, const char *user, const char *pass, char *outBuffer, size_t outSize)
     * }
     */
    public static MethodHandle list_files$handle() {
        return list_files.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int list_files(const char *url, const char *user, const char *pass, char *outBuffer, size_t outSize)
     * }
     */
    public static MemorySegment list_files$address() {
        return list_files.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int list_files(const char *url, const char *user, const char *pass, char *outBuffer, size_t outSize)
     * }
     */
    public static int list_files(MemorySegment url, MemorySegment user, MemorySegment pass, MemorySegment outBuffer, long outSize) {
        var mh$ = list_files.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("list_files", url, user, pass, outBuffer, outSize);
            }
            return (int)mh$.invokeExact(url, user, pass, outBuffer, outSize);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class list_folders {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            sync_h.C_INT,
            sync_h.C_POINTER,
            sync_h.C_POINTER,
            sync_h.C_POINTER
        );

        public static final MemorySegment ADDR = sync_h.findOrThrow("list_folders");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int list_folders(const char *remote_url, const char *username, const char *password)
     * }
     */
    public static FunctionDescriptor list_folders$descriptor() {
        return list_folders.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int list_folders(const char *remote_url, const char *username, const char *password)
     * }
     */
    public static MethodHandle list_folders$handle() {
        return list_folders.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int list_folders(const char *remote_url, const char *username, const char *password)
     * }
     */
    public static MemorySegment list_folders$address() {
        return list_folders.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int list_folders(const char *remote_url, const char *username, const char *password)
     * }
     */
    public static int list_folders(MemorySegment remote_url, MemorySegment username, MemorySegment password) {
        var mh$ = list_folders.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("list_folders", remote_url, username, password);
            }
            return (int)mh$.invokeExact(remote_url, username, password);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class write_callback {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            sync_h.C_LONG,
            sync_h.C_POINTER,
            sync_h.C_LONG,
            sync_h.C_LONG,
            sync_h.C_POINTER
        );

        public static final MemorySegment ADDR = sync_h.findOrThrow("write_callback");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * size_t write_callback(void *ptr, size_t size, size_t nmemb, void *userdata)
     * }
     */
    public static FunctionDescriptor write_callback$descriptor() {
        return write_callback.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * size_t write_callback(void *ptr, size_t size, size_t nmemb, void *userdata)
     * }
     */
    public static MethodHandle write_callback$handle() {
        return write_callback.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * size_t write_callback(void *ptr, size_t size, size_t nmemb, void *userdata)
     * }
     */
    public static MemorySegment write_callback$address() {
        return write_callback.ADDR;
    }

    /**
     * {@snippet lang=c :
     * size_t write_callback(void *ptr, size_t size, size_t nmemb, void *userdata)
     * }
     */
    public static long write_callback(MemorySegment ptr, long size, long nmemb, MemorySegment userdata) {
        var mh$ = write_callback.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("write_callback", ptr, size, nmemb, userdata);
            }
            return (long)mh$.invokeExact(ptr, size, nmemb, userdata);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class list_folders_into_buffer {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            sync_h.C_INT,
            sync_h.C_POINTER,
            sync_h.C_POINTER,
            sync_h.C_POINTER,
            sync_h.C_POINTER,
            sync_h.C_LONG
        );

        public static final MemorySegment ADDR = sync_h.findOrThrow("list_folders_into_buffer");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int list_folders_into_buffer(const char *remote_url, const char *username, const char *password, char *outBuffer, size_t outSize)
     * }
     */
    public static FunctionDescriptor list_folders_into_buffer$descriptor() {
        return list_folders_into_buffer.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int list_folders_into_buffer(const char *remote_url, const char *username, const char *password, char *outBuffer, size_t outSize)
     * }
     */
    public static MethodHandle list_folders_into_buffer$handle() {
        return list_folders_into_buffer.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int list_folders_into_buffer(const char *remote_url, const char *username, const char *password, char *outBuffer, size_t outSize)
     * }
     */
    public static MemorySegment list_folders_into_buffer$address() {
        return list_folders_into_buffer.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int list_folders_into_buffer(const char *remote_url, const char *username, const char *password, char *outBuffer, size_t outSize)
     * }
     */
    public static int list_folders_into_buffer(MemorySegment remote_url, MemorySegment username, MemorySegment password, MemorySegment outBuffer, long outSize) {
        var mh$ = list_folders_into_buffer.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("list_folders_into_buffer", remote_url, username, password, outBuffer, outSize);
            }
            return (int)mh$.invokeExact(remote_url, username, password, outBuffer, outSize);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }
    private static final MemorySegment NULL = MemorySegment.ofAddress(0L);
    /**
     * {@snippet lang=c :
     * #define NULL (void*) 0
     * }
     */
    public static MemorySegment NULL() {
        return NULL;
    }
}

