// Generated by jextract

package com.nativecloud.libcurl;

import java.lang.foreign.*;
import java.util.function.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct curl_certinfo {
 *     int num_of_certs;
 *     struct curl_slist **certinfo;
 * }
 * }
 */
public class curl_certinfo {

    curl_certinfo() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        curl_wrapper_h.C_INT.withName("num_of_certs"),
        MemoryLayout.paddingLayout(4),
        curl_wrapper_h.C_POINTER.withName("certinfo")
    ).withName("curl_certinfo");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt num_of_certs$LAYOUT = (OfInt)$LAYOUT.select(groupElement("num_of_certs"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int num_of_certs
     * }
     */
    public static final OfInt num_of_certs$layout() {
        return num_of_certs$LAYOUT;
    }

    private static final long num_of_certs$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int num_of_certs
     * }
     */
    public static final long num_of_certs$offset() {
        return num_of_certs$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int num_of_certs
     * }
     */
    public static int num_of_certs(MemorySegment struct) {
        return struct.get(num_of_certs$LAYOUT, num_of_certs$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int num_of_certs
     * }
     */
    public static void num_of_certs(MemorySegment struct, int fieldValue) {
        struct.set(num_of_certs$LAYOUT, num_of_certs$OFFSET, fieldValue);
    }

    private static final AddressLayout certinfo$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("certinfo"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct curl_slist **certinfo
     * }
     */
    public static final AddressLayout certinfo$layout() {
        return certinfo$LAYOUT;
    }

    private static final long certinfo$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct curl_slist **certinfo
     * }
     */
    public static final long certinfo$offset() {
        return certinfo$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct curl_slist **certinfo
     * }
     */
    public static MemorySegment certinfo(MemorySegment struct) {
        return struct.get(certinfo$LAYOUT, certinfo$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct curl_slist **certinfo
     * }
     */
    public static void certinfo(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(certinfo$LAYOUT, certinfo$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

