// Generated by jextract

package com.nativecloud.libcurl;

import java.lang.invoke.*;
import java.lang.foreign.*;

/**
 * {@snippet lang=c :
 * typedef CURLSTScode (*curl_hstswrite_callback)(CURL *, struct curl_hstsentry {
 *     char *name;
 *     size_t namelen;
 *     unsigned int includeSubDomains : 1;
 *     char expire[18];
 * } *, struct curl_index {
 *     size_t index;
 *     size_t total;
 * } *, void *)
 * }
 */
public class curl_hstswrite_callback {

    curl_hstswrite_callback() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        int apply(MemorySegment easy, MemorySegment e, MemorySegment i, MemorySegment userp);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        curl_wrapper_h.C_INT,
        curl_wrapper_h.C_POINTER,
        curl_wrapper_h.C_POINTER,
        curl_wrapper_h.C_POINTER,
        curl_wrapper_h.C_POINTER
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = curl_wrapper_h.upcallHandle(curl_hstswrite_callback.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(curl_hstswrite_callback.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static int invoke(MemorySegment funcPtr,MemorySegment easy, MemorySegment e, MemorySegment i, MemorySegment userp) {
        try {
            return (int) DOWN$MH.invokeExact(funcPtr, easy, e, i, userp);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

