// Generated by jextract

package com.nativecloud.libcurl;

import java.lang.foreign.*;
import java.util.function.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct curl_index {
 *     size_t index;
 *     size_t total;
 * }
 * }
 */
public class curl_index {

    curl_index() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        curl_wrapper_h.C_LONG.withName("index"),
        curl_wrapper_h.C_LONG.withName("total")
    ).withName("curl_index");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfLong index$LAYOUT = (OfLong)$LAYOUT.select(groupElement("index"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t index
     * }
     */
    public static final OfLong index$layout() {
        return index$LAYOUT;
    }

    private static final long index$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t index
     * }
     */
    public static final long index$offset() {
        return index$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t index
     * }
     */
    public static long index(MemorySegment struct) {
        return struct.get(index$LAYOUT, index$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t index
     * }
     */
    public static void index(MemorySegment struct, long fieldValue) {
        struct.set(index$LAYOUT, index$OFFSET, fieldValue);
    }

    private static final OfLong total$LAYOUT = (OfLong)$LAYOUT.select(groupElement("total"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t total
     * }
     */
    public static final OfLong total$layout() {
        return total$LAYOUT;
    }

    private static final long total$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t total
     * }
     */
    public static final long total$offset() {
        return total$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t total
     * }
     */
    public static long total(MemorySegment struct) {
        return struct.get(total$LAYOUT, total$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t total
     * }
     */
    public static void total(MemorySegment struct, long fieldValue) {
        struct.set(total$LAYOUT, total$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

