// Generated by jextract

package com.nativecloud.libcurl;

import java.lang.invoke.*;
import java.lang.foreign.*;

/**
 * {@snippet lang=c :
 * typedef int (*curl_prereq_callback)(void *, char *, char *, int, int)
 * }
 */
public class curl_prereq_callback {

    curl_prereq_callback() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        int apply(MemorySegment clientp, MemorySegment conn_primary_ip, MemorySegment conn_local_ip, int conn_primary_port, int conn_local_port);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        curl_wrapper_h.C_INT,
        curl_wrapper_h.C_POINTER,
        curl_wrapper_h.C_POINTER,
        curl_wrapper_h.C_POINTER,
        curl_wrapper_h.C_INT,
        curl_wrapper_h.C_INT
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = curl_wrapper_h.upcallHandle(curl_prereq_callback.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(curl_prereq_callback.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static int invoke(MemorySegment funcPtr,MemorySegment clientp, MemorySegment conn_primary_ip, MemorySegment conn_local_ip, int conn_primary_port, int conn_local_port) {
        try {
            return (int) DOWN$MH.invokeExact(funcPtr, clientp, conn_primary_ip, conn_local_ip, conn_primary_port, conn_local_port);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

