// Generated by jextract

package com.nativecloud.libcurl;

import java.lang.invoke.*;
import java.lang.foreign.*;

/**
 * {@snippet lang=c :
 * typedef void *(*curl_realloc_callback)(void *, size_t)
 * }
 */
public class curl_realloc_callback {

    curl_realloc_callback() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        MemorySegment apply(MemorySegment ptr, long size);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        curl_wrapper_h.C_POINTER,
        curl_wrapper_h.C_POINTER,
        curl_wrapper_h.C_LONG
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = curl_wrapper_h.upcallHandle(curl_realloc_callback.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(curl_realloc_callback.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static MemorySegment invoke(MemorySegment funcPtr,MemorySegment ptr, long size) {
        try {
            return (MemorySegment) DOWN$MH.invokeExact(funcPtr, ptr, size);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

