// Generated by jextract

package com.nativecloud.libcurl;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.util.function.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct curl_hstsentry {
 *     char *name;
 *     size_t namelen;
 *     unsigned int includeSubDomains : 1;
 *     char expire[18];
 * }
 * }
 */
public class curl_hstsentry {

    curl_hstsentry() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        curl_wrapper_h.C_POINTER.withName("name"),
        curl_wrapper_h.C_LONG.withName("namelen"),
        MemoryLayout.paddingLayout(1),
        MemoryLayout.sequenceLayout(18, curl_wrapper_h.C_CHAR).withName("expire"),
        MemoryLayout.paddingLayout(5)
    ).withName("curl_hstsentry");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout name$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("name"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char *name
     * }
     */
    public static final AddressLayout name$layout() {
        return name$LAYOUT;
    }

    private static final long name$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char *name
     * }
     */
    public static final long name$offset() {
        return name$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char *name
     * }
     */
    public static MemorySegment name(MemorySegment struct) {
        return struct.get(name$LAYOUT, name$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char *name
     * }
     */
    public static void name(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(name$LAYOUT, name$OFFSET, fieldValue);
    }

    private static final OfLong namelen$LAYOUT = (OfLong)$LAYOUT.select(groupElement("namelen"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t namelen
     * }
     */
    public static final OfLong namelen$layout() {
        return namelen$LAYOUT;
    }

    private static final long namelen$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t namelen
     * }
     */
    public static final long namelen$offset() {
        return namelen$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t namelen
     * }
     */
    public static long namelen(MemorySegment struct) {
        return struct.get(namelen$LAYOUT, namelen$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t namelen
     * }
     */
    public static void namelen(MemorySegment struct, long fieldValue) {
        struct.set(namelen$LAYOUT, namelen$OFFSET, fieldValue);
    }

    private static final SequenceLayout expire$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("expire"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char expire[18]
     * }
     */
    public static final SequenceLayout expire$layout() {
        return expire$LAYOUT;
    }

    private static final long expire$OFFSET = 17;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char expire[18]
     * }
     */
    public static final long expire$offset() {
        return expire$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char expire[18]
     * }
     */
    public static MemorySegment expire(MemorySegment struct) {
        return struct.asSlice(expire$OFFSET, expire$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char expire[18]
     * }
     */
    public static void expire(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, expire$OFFSET, expire$LAYOUT.byteSize());
    }

    private static long[] expire$DIMS = { 18 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * char expire[18]
     * }
     */
    public static long[] expire$dimensions() {
        return expire$DIMS;
    }
    private static final VarHandle expire$ELEM_HANDLE = expire$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * char expire[18]
     * }
     */
    public static byte expire(MemorySegment struct, long index0) {
        return (byte)expire$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * char expire[18]
     * }
     */
    public static void expire(MemorySegment struct, long index0, byte fieldValue) {
        expire$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

