// Generated by jextract

package com.nativecloud.libcurl;

import java.lang.invoke.*;
import java.lang.foreign.*;

/**
 * {@snippet lang=c :
 * typedef size_t (*curl_write_callback)(char *, size_t, size_t, void *)
 * }
 */
public class curl_write_callback {

    curl_write_callback() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        long apply(MemorySegment buffer, long size, long nitems, MemorySegment outstream);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        curl_wrapper_h.C_LONG,
        curl_wrapper_h.C_POINTER,
        curl_wrapper_h.C_LONG,
        curl_wrapper_h.C_LONG,
        curl_wrapper_h.C_POINTER
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = curl_wrapper_h.upcallHandle(curl_write_callback.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(curl_write_callback.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static long invoke(MemorySegment funcPtr,MemorySegment buffer, long size, long nitems, MemorySegment outstream) {
        try {
            return (long) DOWN$MH.invokeExact(funcPtr, buffer, size, nitems, outstream);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

