// Generated by jextract

package com.nativecloud.libcurl;

import java.lang.foreign.*;
import java.util.function.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct curl_tlssessioninfo {
 *     curl_sslbackend backend;
 *     void *internals;
 * }
 * }
 */
public class curl_tlssessioninfo {

    curl_tlssessioninfo() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        curl_wrapper_h.C_INT.withName("backend"),
        MemoryLayout.paddingLayout(4),
        curl_wrapper_h.C_POINTER.withName("internals")
    ).withName("curl_tlssessioninfo");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt backend$LAYOUT = (OfInt)$LAYOUT.select(groupElement("backend"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * curl_sslbackend backend
     * }
     */
    public static final OfInt backend$layout() {
        return backend$LAYOUT;
    }

    private static final long backend$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * curl_sslbackend backend
     * }
     */
    public static final long backend$offset() {
        return backend$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * curl_sslbackend backend
     * }
     */
    public static int backend(MemorySegment struct) {
        return struct.get(backend$LAYOUT, backend$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * curl_sslbackend backend
     * }
     */
    public static void backend(MemorySegment struct, int fieldValue) {
        struct.set(backend$LAYOUT, backend$OFFSET, fieldValue);
    }

    private static final AddressLayout internals$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("internals"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *internals
     * }
     */
    public static final AddressLayout internals$layout() {
        return internals$LAYOUT;
    }

    private static final long internals$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *internals
     * }
     */
    public static final long internals$offset() {
        return internals$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *internals
     * }
     */
    public static MemorySegment internals(MemorySegment struct) {
        return struct.get(internals$LAYOUT, internals$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *internals
     * }
     */
    public static void internals(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(internals$LAYOUT, internals$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

