// Generated by jextract

package com.nativecloud.libcurl;

import java.lang.invoke.*;
import java.lang.foreign.*;

/**
 * {@snippet lang=c :
 * typedef void (*curl_unlock_function)(CURL *, curl_lock_data, void *)
 * }
 */
public class curl_unlock_function {

    curl_unlock_function() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        void apply(MemorySegment handle, int data, MemorySegment userptr);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
        curl_wrapper_h.C_POINTER,
        curl_wrapper_h.C_INT,
        curl_wrapper_h.C_POINTER
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = curl_wrapper_h.upcallHandle(curl_unlock_function.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(curl_unlock_function.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static void invoke(MemorySegment funcPtr,MemorySegment handle, int data, MemorySegment userptr) {
        try {
             DOWN$MH.invokeExact(funcPtr, handle, data, userptr);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

